OpenLoyalty\Domain\Campaign\Campaign:
  type: entity
  repositoryClass: OpenLoyalty\Infrastructure\Campaign\Persistance\Doctrine\Repository\DoctrineCampaignRepository
  table: ol__campaign
  id:
    campaignId:
      type: campaign_id
      column: campaign_id
  fields:
    reward:
      type: string
    name:
      type: string
    shortDescription:
      type: text
      nullable: true
      column: short_description
    conditionsDescription:
      type: text
      nullable: true
      column: conditions_description
    usageInstruction:
      type: text
      nullable: true
      column: usage_instruction
    active:
      type: boolean
      options:
        default: 0
    costInPoints:
      type: integer
      column: cost_in_points
    levels:
      type: campaign_levels_json_array
    segments:
      type: campaign_segments_json_array
    unlimited:
      type: boolean
      options:
        default: 1
    singleCoupon:
      type: boolean
      options:
        default: 1
    limit:
      type: integer
      nullable: true
      column: usage_limit
    limitPerUser:
      type: integer
      nullable: true
      column: limit_per_user
    coupons:
      type: campaign_coupons_json_array
  embedded:
    campaignActivity:
      class: OpenLoyalty\Domain\Campaign\Model\CampaignActivity
    campaignVisibility:
      class: OpenLoyalty\Domain\Campaign\Model\CampaignVisibility
    campaignPhoto:
      class: OpenLoyalty\Domain\Campaign\Model\CampaignPhoto