backend:
  container_name: open_loyalty_backend
  build: ./backend
  links:
    - elk
    - db
    - mail
  ports:
    - "8181:80"
  extra_hosts:
    - "web:127.0.0.1"
frontend:
  container_name: open_loyalty_frontend
  build: ./frontend
  ports:
    - "8182:3000"
    - "8183:3001"
    - "8184:3002"
elk:
  container_name: open_loyalty_elk
  image: elasticsearch:2.2
db:
  container_name: open_loyalty_postgresql
  image: postgres:9
  environment:
    - POSTGRES_DB=openloyalty
    - POSTGRES_USER=openloyalty
    - POSTGRES_PASSWORD=openloyalty
mail:
  container_name: open_loyalty_mail
  image: mailhog/mailhog
  ports:
    - "8186:8025"
