OpenLoyalty\Domain\Segment\Segment:
  type: entity
  repositoryClass: OpenLoyalty\Infrastructure\Segment\Persistance\Doctrine\Repository\DoctrineSegmentRepository
  table: ol__segment
  id:
    segmentId:
      type: segment_id
      column: segment_id
  fields:
    name:
      type: string
      column: name
      unique: true
    description:
      type: text
      nullable: true
      column: description
    active:
      type: boolean
      options:
        default: 0
    customersCount:
      type: integer
      options:
        default: 0
      column: customers_count
    createdAt:
      type: datetime
      column: created_at
      nullable: true
  oneToMany:
    parts:
      targetEntity: OpenLoyalty\Domain\Segment\Model\SegmentPart
      mappedBy: segment
      cascade: ["all"]
      orphanRemoval: true