OpenLoyalty\Domain\EarningRule\EventEarningRule:
  type: entity
  fields:
    eventName:
      type: string
      column: event_name
    pointsAmount:
      type: decimal
      scale: 2
      precision: 14
      column: points_amount
