version: "2"

services:
  php:
    build:
      context: '../'
      dockerfile: './docker/dev/php/fpm-dockerfile'
    links:
      - db
      - elk
      - mail
    ports:
      - "9000:9000"
    volumes:
        - '../backend:/var/www/openloyalty'
  nginx:
    build:
      context: '../'
      dockerfile: './docker/dev/web/backend-dockerfile'
    links:
      - php
    ports:
      - "80:80"
  frontend:
    container_name: open_loyalty_frontend_dev
    build:
      context: '../'
      dockerfile: './docker/dev/web/front-dockerfile'
    ports:
      - "8081:8081"
    volumes:
      - '../frontend/:/var/www/frontend'
      - './dev/web/config.js:/var/www/frontend/src/config.js'
